# Generated by Django 4.2.7 on 2026-03-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='label',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('Health', 'Health'), ('Learning', 'Learning'), ('Home', 'Home'), ('Errands', 'Errands')], default='Personal', max_length=50),
        ),
        migrations.AddField(
            model_name='todo',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
